# Generated by Django 2.0.1 on 2018-07-10 01:21

from decimal import Decimal
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import exchange_core.managers
import exchange_core.models
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    replaces = [('exchange_core', '0001_initial'), ('exchange_core', '0002_auto_20180106_1530'), ('exchange_core', '0003_auto_20180106_1806'), ('exchange_core', '0004_documents'), ('exchange_core', '0005_auto_20180116_1424'), ('exchange_core', '0006_auto_20180116_1427'), ('exchange_core', '0007_auto_20180118_0243'), ('exchange_core', '0008_statement'), ('exchange_core', '0009_auto_20180130_1958'), ('exchange_core', '0010_users_profile'), ('exchange_core', '0011_auto_20180204_1555'), ('exchange_core', '0012_statement_tx_id'), ('exchange_core', '0013_auto_20180209_1546'), ('exchange_core', '0014_auto_20180212_0132'), ('exchange_core', '0015_auto_20180212_0150'), ('exchange_core', '0016_auto_20180218_2204'), ('exchange_core', '0017_auto_20180301_1147'), ('exchange_core', '0018_auto_20180301_1417'), ('exchange_core', '0019_auto_20180302_1207'), ('exchange_core', '0020_auto_20180302_1635'), ('exchange_core', '0021_auto_20180302_1652'), ('exchange_core', '0022_documents_reason'), ('exchange_core', '0023_auto_20180302_1716'), ('exchange_core', '0024_auto_20180306_1642'), ('exchange_core', '0025_auto_20180306_1651'), ('exchange_core', '0024_auto_20180306_1427'), ('exchange_core', '0026_merge_20180306_2023'), ('exchange_core', '0027_auto_20180308_1516'), ('exchange_core', '0028_auto_20180314_1801'), ('exchange_core', '0029_auto_20180319_2348'), ('exchange_core', '0030_auto_20180320_1403'), ('exchange_core', '0031_auto_20180320_1529'), ('exchange_core', '0032_auto_20180322_1150'), ('exchange_core', '0033_auto_20180323_0059'), ('exchange_core', '0034_auto_20180325_1451'), ('exchange_core', '0035_auto_20180328_1436'), ('exchange_core', '0036_remove_users_sponsor'), ('exchange_core', '0037_auto_20180520_1731'), ('exchange_core', '0038_auto_20180520_1742'), ('exchange_core', '0039_auto_20180525_1552'), ('exchange_core', '0040_addresses_complement'), ('exchange_core', '0041_auto_20180528_0812'), ('exchange_core', '0042_accounts_address_id'), ('exchange_core', '0043_auto_20180625_1350'), ('exchange_core', '0044_users_is_test'), ('exchange_core', '0045_auto_20180704_1714'), ('exchange_core', '0046_auto_20180704_1720'), ('exchange_core', '0047_auto_20180706_1407')]

    initial = True

    dependencies = [
        ('cities', '__first__'),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('cities', '0011_auto_20180108_0706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='created', max_length=30, verbose_name='Status')),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sponsor')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deposit', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('reserved', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20)),
                ('deposit_address', models.CharField(blank=True, max_length=255, null=True)),
                ('withdraw_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Currency Account',
                'verbose_name_plural': 'Currencies Accounts',
                'ordering': ['currency__name'],
            },
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('symbol', models.CharField(max_length=10)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=exchange_core.models.get_file_path, verbose_name='Icon')),
                ('withdraw_fee', models.DecimalField(decimal_places=8, default=Decimal('0.005'), max_digits=20, verbose_name='Withdraw Percent Fee')),
                ('withdraw_max', models.DecimalField(decimal_places=8, default=Decimal('1000000.00'), max_digits=20, verbose_name='Withdraw Max')),
                ('withdraw_min', models.DecimalField(decimal_places=8, default=Decimal('0.001'), max_digits=20, verbose_name='Withdraw Min')),
                ('withdraw_receive_hours', models.IntegerField(default=48)),
                ('withdraw_fixed_fee', models.DecimalField(decimal_places=8, default=Decimal('0.005'), max_digits=20, verbose_name='Withdraw Fixed Fee')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=30, verbose_name='Status')),
                ('order', models.IntegerField(default=100, verbose_name='Order')),
                ('type', models.CharField(choices=[('checking', 'checking'), ('investment', 'investment')], default='checking', max_length=20)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='accounts',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='exchange_core.Currencies', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='withdraw_address',
        ),
        migrations.CreateModel(
            name='BankAccounts',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank', models.CharField(choices=[('1', '1 - Banco do Brasil S.A.'), ('3', '3 - Banco da Amazônia S.A.'), ('4', '4 - Banco do Nordeste do Brasil S.A.'), ('12', '12 - Banco Standard de Investimentos S.A.'), ('14', '14 - Natixis Brasil S.A. Banco Múltiplo'), ('18', '18 - Banco Tricury S.A.'), ('19', '19 - Banco Azteca do Brasil S.A.'), ('21', '21 - BANESTES S.A. Banco do Estado do Espírito Santo'), ('24', '24 - Banco BANDEPE S.A.'), ('25', '25 - Banco Alfa S.A.'), ('29', '29 - Banco Banerj S.A.'), ('31', '31 - Banco Beg S.A.'), ('33', '33 - Banco Santander (Brasil) S.A.'), ('36', '36 - Banco Bradesco BBI S.A.'), ('37', '37 - Banco do Estado do Pará S.A.'), ('39', '39 - Banco do Estado do Piauí S.A. - BEP'), ('40', '40 - Banco Cargill S.A.'), ('41', '41 - Banco do Estado do Rio Grande do Sul S.A.'), ('44', '44 - Banco BVA S.A.'), ('45', '45 - Banco Opportunity S.A.'), ('47', '47 - Banco do Estado de Sergipe S.A.'), ('62', '62 - Hipercard Banco Múltiplo S.A.'), ('63', '63 - Banco Ibi S.A. Banco Múltiplo'), ('64', '64 - Goldman Sachs do Brasil Banco Múltiplo S.A.'), ('65', '65 - Banco AndBank (Brasil) S.A.'), ('66', '66 - Banco Morgan Stanley S.A.'), ('69', '69 - BPN Brasil Banco Múltiplo S.A.'), ('70', '70 - BRB - Banco de Brasília S.A.'), ('72', '72 - Banco Rural Mais S.A.'), ('73', '73 - BB Banco Popular do Brasil S.A.'), ('74', '74 - Banco J. Safra S.A.'), ('75', '75 - Banco ABN AMRO S.A.'), ('76', '76 - Banco KDB S.A.'), ('77', '77 - Banco Intermedium S.A.'), ('78', '78 - BES Investimento do Brasil S.A.-Banco de Investimento'), ('79', '79 - Banco Original do Agronegócio S.A.'), ('81', '81 - BBN Banco Brasileiro de Negócios S.A.'), ('82', '82 - Banco Topázio S.A.'), ('83', '83 - Banco da China Brasil S.A.'), ('85', '85 - Cooperativa Central de Crédito Urbano-CECRED'), ('86', '86 - OBOE Crédito Financiamento e Investimento S.A.'), ('87', '87 - Cooperativa Unicred Central Santa Catarina'), ('88', '88 - Banco Randon S.A.'), ('89', '89 - Cooperativa de Crédito Rural da Região de Mogiana'), ('90', '90 - Cooperativa Central de Economia e Crédito Mutuo das Unicreds'), ('91', '91 - Unicred Central do Rio Grande do Sul'), ('92', '92 - Brickell S.A. Crédito, financiamento e Investimento'), ('94', '94 - Banco Petra S.A.'), ('95', '95 - Banco Confidence de Câmbio S.A.'), ('96', '96 - Banco BM&FBOVESPA de Serviços de Liquidação e Custódia S.A'), ('97', '97 - Cooperativa Central de Crédito Noroeste Brasileiro Ltda.'), ('98', '98 - CREDIALIANÇA COOPERATIVA DE CRÉDITO RURAL'), ('99', '99 - Cooperativa Central de Economia e Credito Mutuo das Unicreds'), ('104', '104 - Caixa Econômica Federal'), ('107', '107 - Banco BBM S.A.'), ('114', '114 - Central das Coop. de Economia e Crédito Mutuo do Est. do ES'), ('119', '119 - Banco Western Union do Brasil S.A.'), ('122', '122 - Banco BERJ S.A.'), ('125', '125 - Brasil Plural S.A. - Banco Múltiplo'), ('136', '136 - CONFEDERACAO NACIONAL DAS COOPERATIVAS CENTRAIS UNICREDS'), ('168', '168 - HSBC Finance (Brasil) S.A. - Banco Múltiplo'), ('184', '184 - Banco Itaú BBA S.A.'), ('204', '204 - Banco Bradesco Cartões S.A.'), ('208', '208 - Banco BTG Pactual S.A.'), ('212', '212 - Banco Original S.A.'), ('213', '213 - Banco Arbi S.A.'), ('214', '214 - Banco Dibens S.A.'), ('215', '215 - Banco Comercial e de Investimento Sudameris S.A.'), ('217', '217 - Banco John Deere S.A.'), ('218', '218 - Banco Bonsucesso S.A.'), ('222', '222 - Banco Credit Agricole Brasil S.A.'), ('224', '224 - Banco Fibra S.A.'), ('225', '225 - Banco Brascan S.A.'), ('229', '229 - Banco Cruzeiro do Sul S.A.'), ('230', '230 - Unicard Banco Múltiplo S.A.'), ('233', '233 - Banco Cifra S.A.'), ('237', '237 - Banco Bradesco S.A.'), ('241', '241 - Banco Clássico S.A.'), ('243', '243 - Banco Máxima S.A.'), ('246', '246 - Banco ABC Brasil S.A.'), ('248', '248 - Banco Boavista Interatlântico S.A.'), ('249', '249 - Banco Investcred Unibanco S.A.'), ('250', '250 - BCV - Banco de Crédito e Varejo S.A.'), ('254', '254 - Paraná Banco S.A.'), ('263', '263 - Banco Cacique S.A.'), ('265', '265 - Banco Fator S.A.'), ('266', '266 - Banco Cédula S.A.'), ('300', '300 - Banco de La Nacion Argentina'), ('318', '318 - Banco BMG S.A.'), ('320', '320 - Banco Industrial e Comercial S.A.'), ('341', '341 - Itaú Unibanco S.A.'), ('356', '356 - Banco Real S.A.'), ('366', '366 - Banco Société Générale Brasil S.A.'), ('370', '370 - Banco Mizuho do Brasil S.A.'), ('376', '376 - Banco J. P. Morgan S.A.'), ('389', '389 - Banco Mercantil do Brasil S.A.'), ('394', '394 - Banco Bradesco Financiamentos S.A.'), ('399', '399 - HSBC Bank Brasil S.A. - Banco Múltiplo'), ('409', '409 - UNIBANCO - União de Bancos Brasileiros S.A.'), ('412', '412 - Banco Capital S.A.'), ('422', '422 - Banco Safra S.A.'), ('453', '453 - Banco Rural S.A.'), ('456', '456 - Banco de Tokyo-Mitsubishi UFJ Brasil S.A.'), ('464', '464 - Banco Sumitomo Mitsui Brasileiro S.A.'), ('473', '473 - Banco Caixa Geral - Brasil S.A.'), ('477', '477 - CitiBank S.A.'), ('479', '479 - Banco ItaúBank S.A'), ('487', '487 - Deutsche Bank S.A. - Banco Alemão'), ('488', '488 - JPMorgan Chase Bank'), ('492', '492 - ING Bank N.V.'), ('494', '494 - Banco de La Republica Oriental del Uruguay'), ('495', '495 - Banco de La Provincia de Buenos Aires'), ('505', '505 - Banco Credit Suisse (Brasil) S.A.'), ('600', '600 - Banco Luso Brasileiro S.A.'), ('604', '604 - Banco Industrial do Brasil S.A.'), ('610', '610 - Banco VR S.A.'), ('611', '611 - Banco Paulista S.A.'), ('612', '612 - Banco Guanabara S.A.'), ('613', '613 - Banco Pecúnia S.A.'), ('623', '623 - Banco PAN S.A.'), ('626', '626 - Banco Ficsa S.A.'), ('630', '630 - Banco Intercap S.A.'), ('633', '633 - Banco Rendimento S.A.'), ('634', '634 - Banco Triângulo S.A.'), ('637', '637 - Banco Sofisa S.A.'), ('638', '638 - Banco Prosper S.A.'), ('641', '641 - Banco Alvorada S.A.'), ('643', '643 - Banco Pine S.A.'), ('652', '652 - Itaú Unibanco Holding S.A.'), ('653', '653 - Banco Indusval S.A.'), ('654', '654 - Banco A.J.Renner S.A.'), ('655', '655 - Banco Votorantim S.A.'), ('707', '707 - Banco Daycoval S.A.'), ('712', '712 - Banco Ourinvest S.A.'), ('719', '719 - Banif-Banco Internacional do Funchal (Brasil)S.A.'), ('721', '721 - Banco Credibel S.A.'), ('724', '724 - Banco Porto Seguro S.A.'), ('734', '734 - Banco Gerdau S.A.'), ('735', '735 - Banco Pottencial S.A.'), ('738', '738 - Banco Morada S.A.'), ('739', '739 - Banco Cetelem S.A.'), ('740', '740 - Banco Barclays S.A.'), ('741', '741 - Banco Ribeirão Preto S.A.'), ('743', '743 - Banco Semear S.A.'), ('744', '744 - BankBoston N.A.'), ('745', '745 - Banco CitiBank S.A.'), ('746', '746 - Banco Modal S.A.'), ('747', '747 - Banco RaboBank International Brasil S.A.'), ('748', '748 - Banco Cooperativo Sicredi S.A.'), ('749', '749 - Banco Simples S.A.'), ('751', '751 - ScotiaBank Brasil S.A. Banco Múltiplo'), ('752', '752 - Banco BNP Paribas Brasil S.A.'), ('753', '753 - NBC Bank Brasil S.A. - Banco Múltiplo'), ('755', '755 - Bank of America Merrill Lynch Banco Múltiplo S.A.'), ('756', '756 - Banco Cooperativo do Brasil S.A. - BANCOOB'), ('757', '757 - Banco KEB do Brasil S.A.')], max_length=10, verbose_name='Bank')),
                ('agency', models.CharField(max_length=10, verbose_name='Agency')),
                ('account_type', models.CharField(choices=[('corrente', 'Corrente'), ('poupanca', 'Poupança')], max_length=20, verbose_name='Account type')),
                ('account_number', models.CharField(max_length=20, verbose_name='Account number')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='exchange_core.Accounts', verbose_name='Account')),
                ('account_number_digit', models.CharField(max_length=5, null=True, verbose_name='Digit')),
                ('agency_digit', models.CharField(max_length=5, null=True, verbose_name='Digit')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Bank account',
                'verbose_name_plural': 'Bank accounts',
            },
        ),
        migrations.CreateModel(
            name='BankWithdraw',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deposit', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Deposit')),
                ('reserved', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Reserved')),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Amount')),
                ('status', models.CharField(choices=[('requested', 'requested'), ('reversed', 'reversed'), ('paid', 'paid')], default='requested', max_length=20, verbose_name='Status')),
                ('bank', models.CharField(choices=[('1', '1 - Banco do Brasil S.A.'), ('3', '3 - Banco da Amazônia S.A.'), ('4', '4 - Banco do Nordeste do Brasil S.A.'), ('12', '12 - Banco Standard de Investimentos S.A.'), ('14', '14 - Natixis Brasil S.A. Banco Múltiplo'), ('18', '18 - Banco Tricury S.A.'), ('19', '19 - Banco Azteca do Brasil S.A.'), ('21', '21 - BANESTES S.A. Banco do Estado do Espírito Santo'), ('24', '24 - Banco BANDEPE S.A.'), ('25', '25 - Banco Alfa S.A.'), ('29', '29 - Banco Banerj S.A.'), ('31', '31 - Banco Beg S.A.'), ('33', '33 - Banco Santander (Brasil) S.A.'), ('36', '36 - Banco Bradesco BBI S.A.'), ('37', '37 - Banco do Estado do Pará S.A.'), ('39', '39 - Banco do Estado do Piauí S.A. - BEP'), ('40', '40 - Banco Cargill S.A.'), ('41', '41 - Banco do Estado do Rio Grande do Sul S.A.'), ('44', '44 - Banco BVA S.A.'), ('45', '45 - Banco Opportunity S.A.'), ('47', '47 - Banco do Estado de Sergipe S.A.'), ('62', '62 - Hipercard Banco Múltiplo S.A.'), ('63', '63 - Banco Ibi S.A. Banco Múltiplo'), ('64', '64 - Goldman Sachs do Brasil Banco Múltiplo S.A.'), ('65', '65 - Banco AndBank (Brasil) S.A.'), ('66', '66 - Banco Morgan Stanley S.A.'), ('69', '69 - BPN Brasil Banco Múltiplo S.A.'), ('70', '70 - BRB - Banco de Brasília S.A.'), ('72', '72 - Banco Rural Mais S.A.'), ('73', '73 - BB Banco Popular do Brasil S.A.'), ('74', '74 - Banco J. Safra S.A.'), ('75', '75 - Banco ABN AMRO S.A.'), ('76', '76 - Banco KDB S.A.'), ('77', '77 - Banco Intermedium S.A.'), ('78', '78 - BES Investimento do Brasil S.A.-Banco de Investimento'), ('79', '79 - Banco Original do Agronegócio S.A.'), ('81', '81 - BBN Banco Brasileiro de Negócios S.A.'), ('82', '82 - Banco Topázio S.A.'), ('83', '83 - Banco da China Brasil S.A.'), ('85', '85 - Cooperativa Central de Crédito Urbano-CECRED'), ('86', '86 - OBOE Crédito Financiamento e Investimento S.A.'), ('87', '87 - Cooperativa Unicred Central Santa Catarina'), ('88', '88 - Banco Randon S.A.'), ('89', '89 - Cooperativa de Crédito Rural da Região de Mogiana'), ('90', '90 - Cooperativa Central de Economia e Crédito Mutuo das Unicreds'), ('91', '91 - Unicred Central do Rio Grande do Sul'), ('92', '92 - Brickell S.A. Crédito, financiamento e Investimento'), ('94', '94 - Banco Petra S.A.'), ('95', '95 - Banco Confidence de Câmbio S.A.'), ('96', '96 - Banco BM&FBOVESPA de Serviços de Liquidação e Custódia S.A'), ('97', '97 - Cooperativa Central de Crédito Noroeste Brasileiro Ltda.'), ('98', '98 - CREDIALIANÇA COOPERATIVA DE CRÉDITO RURAL'), ('99', '99 - Cooperativa Central de Economia e Credito Mutuo das Unicreds'), ('104', '104 - Caixa Econômica Federal'), ('107', '107 - Banco BBM S.A.'), ('114', '114 - Central das Coop. de Economia e Crédito Mutuo do Est. do ES'), ('119', '119 - Banco Western Union do Brasil S.A.'), ('122', '122 - Banco BERJ S.A.'), ('125', '125 - Brasil Plural S.A. - Banco Múltiplo'), ('136', '136 - CONFEDERACAO NACIONAL DAS COOPERATIVAS CENTRAIS UNICREDS'), ('168', '168 - HSBC Finance (Brasil) S.A. - Banco Múltiplo'), ('184', '184 - Banco Itaú BBA S.A.'), ('204', '204 - Banco Bradesco Cartões S.A.'), ('208', '208 - Banco BTG Pactual S.A.'), ('212', '212 - Banco Original S.A.'), ('213', '213 - Banco Arbi S.A.'), ('214', '214 - Banco Dibens S.A.'), ('215', '215 - Banco Comercial e de Investimento Sudameris S.A.'), ('217', '217 - Banco John Deere S.A.'), ('218', '218 - Banco Bonsucesso S.A.'), ('222', '222 - Banco Credit Agricole Brasil S.A.'), ('224', '224 - Banco Fibra S.A.'), ('225', '225 - Banco Brascan S.A.'), ('229', '229 - Banco Cruzeiro do Sul S.A.'), ('230', '230 - Unicard Banco Múltiplo S.A.'), ('233', '233 - Banco Cifra S.A.'), ('237', '237 - Banco Bradesco S.A.'), ('241', '241 - Banco Clássico S.A.'), ('243', '243 - Banco Máxima S.A.'), ('246', '246 - Banco ABC Brasil S.A.'), ('248', '248 - Banco Boavista Interatlântico S.A.'), ('249', '249 - Banco Investcred Unibanco S.A.'), ('250', '250 - BCV - Banco de Crédito e Varejo S.A.'), ('254', '254 - Paraná Banco S.A.'), ('263', '263 - Banco Cacique S.A.'), ('265', '265 - Banco Fator S.A.'), ('266', '266 - Banco Cédula S.A.'), ('300', '300 - Banco de La Nacion Argentina'), ('318', '318 - Banco BMG S.A.'), ('320', '320 - Banco Industrial e Comercial S.A.'), ('341', '341 - Itaú Unibanco S.A.'), ('356', '356 - Banco Real S.A.'), ('366', '366 - Banco Société Générale Brasil S.A.'), ('370', '370 - Banco Mizuho do Brasil S.A.'), ('376', '376 - Banco J. P. Morgan S.A.'), ('389', '389 - Banco Mercantil do Brasil S.A.'), ('394', '394 - Banco Bradesco Financiamentos S.A.'), ('399', '399 - HSBC Bank Brasil S.A. - Banco Múltiplo'), ('409', '409 - UNIBANCO - União de Bancos Brasileiros S.A.'), ('412', '412 - Banco Capital S.A.'), ('422', '422 - Banco Safra S.A.'), ('453', '453 - Banco Rural S.A.'), ('456', '456 - Banco de Tokyo-Mitsubishi UFJ Brasil S.A.'), ('464', '464 - Banco Sumitomo Mitsui Brasileiro S.A.'), ('473', '473 - Banco Caixa Geral - Brasil S.A.'), ('477', '477 - CitiBank S.A.'), ('479', '479 - Banco ItaúBank S.A'), ('487', '487 - Deutsche Bank S.A. - Banco Alemão'), ('488', '488 - JPMorgan Chase Bank'), ('492', '492 - ING Bank N.V.'), ('494', '494 - Banco de La Republica Oriental del Uruguay'), ('495', '495 - Banco de La Provincia de Buenos Aires'), ('505', '505 - Banco Credit Suisse (Brasil) S.A.'), ('600', '600 - Banco Luso Brasileiro S.A.'), ('604', '604 - Banco Industrial do Brasil S.A.'), ('610', '610 - Banco VR S.A.'), ('611', '611 - Banco Paulista S.A.'), ('612', '612 - Banco Guanabara S.A.'), ('613', '613 - Banco Pecúnia S.A.'), ('623', '623 - Banco PAN S.A.'), ('626', '626 - Banco Ficsa S.A.'), ('630', '630 - Banco Intercap S.A.'), ('633', '633 - Banco Rendimento S.A.'), ('634', '634 - Banco Triângulo S.A.'), ('637', '637 - Banco Sofisa S.A.'), ('638', '638 - Banco Prosper S.A.'), ('641', '641 - Banco Alvorada S.A.'), ('643', '643 - Banco Pine S.A.'), ('652', '652 - Itaú Unibanco Holding S.A.'), ('653', '653 - Banco Indusval S.A.'), ('654', '654 - Banco A.J.Renner S.A.'), ('655', '655 - Banco Votorantim S.A.'), ('707', '707 - Banco Daycoval S.A.'), ('712', '712 - Banco Ourinvest S.A.'), ('719', '719 - Banif-Banco Internacional do Funchal (Brasil)S.A.'), ('721', '721 - Banco Credibel S.A.'), ('724', '724 - Banco Porto Seguro S.A.'), ('734', '734 - Banco Gerdau S.A.'), ('735', '735 - Banco Pottencial S.A.'), ('738', '738 - Banco Morada S.A.'), ('739', '739 - Banco Cetelem S.A.'), ('740', '740 - Banco Barclays S.A.'), ('741', '741 - Banco Ribeirão Preto S.A.'), ('743', '743 - Banco Semear S.A.'), ('744', '744 - BankBoston N.A.'), ('745', '745 - Banco CitiBank S.A.'), ('746', '746 - Banco Modal S.A.'), ('747', '747 - Banco RaboBank International Brasil S.A.'), ('748', '748 - Banco Cooperativo Sicredi S.A.'), ('749', '749 - Banco Simples S.A.'), ('751', '751 - ScotiaBank Brasil S.A. Banco Múltiplo'), ('752', '752 - Banco BNP Paribas Brasil S.A.'), ('753', '753 - NBC Bank Brasil S.A. - Banco Múltiplo'), ('755', '755 - Bank of America Merrill Lynch Banco Múltiplo S.A.'), ('756', '756 - Banco Cooperativo do Brasil S.A. - BANCOOB'), ('757', '757 - Banco KEB do Brasil S.A.')], max_length=10, verbose_name='Bank')),
                ('agency', models.CharField(max_length=10, verbose_name='Agency')),
                ('account_type', models.CharField(choices=[('corrente', 'Corrente'), ('poupanca', 'Poupança')], max_length=20, verbose_name='Account type')),
                ('account_number', models.CharField(max_length=20, verbose_name='Account number')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_withdraw', to='exchange_core.Accounts', verbose_name='Account')),
                ('tx_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Transaction id')),
                ('fee', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Fee')),
                ('account_number_digit', models.CharField(max_length=5, null=True, verbose_name='Digit')),
                ('agency_digit', models.CharField(max_length=5, null=True, verbose_name='Digit')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=100, null=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Bank withdraw',
                'verbose_name_plural': 'Bank withdrawals',
            },
        ),
        migrations.CreateModel(
            name='CryptoWithdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Deposit')),
                ('reserved', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Reserved')),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Amount')),
                ('status', models.CharField(choices=[('requested', 'requested'), ('reversed', 'reversed'), ('paid', 'paid')], default='requested', max_length=20, verbose_name='Status')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_withdraw', to='exchange_core.Accounts', verbose_name='Account')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tx_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Transaction id')),
                ('fee', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Fee')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=100, null=True, verbose_name='Description')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Crypto withdraw',
                'verbose_name_plural': 'Crypto withdrawals',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to=exchange_core.models.get_file_path, verbose_name='File')),
                ('type', models.CharField(choices=[('id_front', 'id_front'), ('id_back', 'id_back'), ('selfie', 'selfie'), ('contract', 'contract'), ('residence', 'residence')], max_length=20, verbose_name='Type')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('disapproved', 'disapproved'), ('approved', 'approved')], default='pending', max_length=20, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('reason', models.CharField(blank=True, max_length=100, null=True, verbose_name='Disapproved reason')),
            ],
            options={
                'abstract': False,
                'ordering': ['status'],
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Amount')),
                ('type', models.CharField(choices=[('deposit', 'deposit'), ('reverse', 'reverse'), ('withdraw', 'withdraw'), ('income', 'income'), ('investment', 'investment'), ('tbsa', 'tbsa'), ('course_subscription', 'course_subscription')], max_length=30, verbose_name='Type')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement', to='exchange_core.Accounts', verbose_name='Account')),
                ('tx_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Transaction id')),
                ('fk', models.UUIDField(blank=True, editable=False, null=True, verbose_name='Foreign key')),
            ],
            options={
                'verbose_name': 'Statement',
                'verbose_name_plural': 'Statement',
            },
        ),
        migrations.AddField(
            model_name='users',
            name='profile',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', exchange_core.managers.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=20)),
                ('neighborhood', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('account', 'account')], default='account', max_length=20)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.CITIES_CITY_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.CITIES_COUNTRY_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='cities.Region')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('document_1', models.CharField(blank=True, max_length=50, null=True)),
                ('document_2', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='users',
            name='document_1',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Document 1'),
        ),
        migrations.AddField(
            model_name='users',
            name='document_2',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Document 2'),
        ),
        migrations.AddField(
            model_name='users',
            name='type',
            field=models.CharField(choices=[('person', 'Person'), ('company', 'Company')], default='person', max_length=11, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('approved_documentation', 'approved_documentation'), ('inactive', 'inactive')], default='created', max_length=30, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='companies',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addresses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('approved_documentation', 'approved_documentation'), ('inactive', 'inactive'), ('disapproved_documentation', 'disapproved_documentation')], default='created', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('approved_documentation', 'approved_documentation'), ('inactive', 'inactive'), ('disapproved_documentation', 'disapproved_documentation')], default='created', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=exchange_core.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.CITIES_CITY_MODEL, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.CITIES_COUNTRY_MODEL, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='neighborhood',
            field=models.CharField(max_length=50, verbose_name='neighborhood'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='cities.Region', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='type',
            field=models.CharField(choices=[('account', 'account')], default='account', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='zipcode',
            field=models.CharField(max_length=10, verbose_name='Zipcode'),
        ),
        migrations.AddField(
            model_name='users',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile phone'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='neighborhood',
            field=models.CharField(max_length=50, verbose_name='Neighborhood'),
        ),
        migrations.AlterUniqueTogether(
            name='currencies',
            unique_together={('symbol', 'type')},
        ),
        migrations.AlterModelOptions(
            name='accounts',
            options={'ordering': ['currency__name'], 'verbose_name': 'Currency account', 'verbose_name_plural': 'Currencies accounts'},
        ),
        migrations.AlterModelOptions(
            name='addresses',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='accounts',
            name='deposit',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Deposit'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='deposit_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Deposit address'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='reserved',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Reserved'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='document_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Document 1'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='document_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Document 2'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Fancy name'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='symbol',
            field=models.CharField(max_length=10, verbose_name='Symbol'),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='type',
            field=models.CharField(choices=[('checking', 'checking'), ('investment', 'investment')], default='checking', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='withdraw_receive_hours',
            field=models.IntegerField(default=48, verbose_name='Withdraw receive hours'),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=exchange_core.models.get_file_path, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True, verbose_name='Profile data'),
        ),
        migrations.RemoveField(
            model_name='users',
            name='sponsor',
        ),
        migrations.AddField(
            model_name='currencies',
            name='tbsa_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), help_text='Transfer between system accounts', max_digits=20, verbose_name='TBSA Percent Fee'),
        ),
        migrations.AddField(
            model_name='currencies',
            name='tbsa_fixed_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), help_text='Transfer between system accounts', max_digits=20, verbose_name='TBSA Fixed Fee'),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='withdraw_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Withdraw Percent Fee'),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='withdraw_fixed_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Withdraw Fixed Fee'),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='withdraw_min',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=20, verbose_name='Withdraw Min'),
        ),
        migrations.AddField(
            model_name='addresses',
            name='complement',
            field=models.CharField(max_length=50, null=True, verbose_name='Complement'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='address_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address ID'),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('inactive', 'Inactive'), ('approved_documentation', 'Approved documentation'), ('disapproved_documentation', 'Disapproved documentation')], default='created', max_length=30, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='users',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
