# Generated by Django 2.0 on 2018-01-06 15:30

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawals',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=8,
                                                default=Decimal('0.00'), max_digits=20)),
                ('amount', models.DecimalField(decimal_places=8,
                                               default=Decimal('0.00'), max_digits=20)),
                ('status', models.CharField(default='requested', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='withdraw_address',
        ),
        migrations.AddField(
            model_name='withdrawals',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='withdrawals', to='exchange_core.Accounts'),
        ),
    ]
