# Generated by Django 2.1.1 on 2018-09-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='prefix',
            field=models.CharField(blank=True, help_text='This will be appended before the amount of this currency in the entire system', max_length=10, null=True, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='sufix',
            field=models.CharField(blank=True, help_text='This will be appended after the amount of this currency in the entire system', max_length=10, null=True, verbose_name='Sufix'),
        ),
        migrations.AlterField(
            model_name='historicalcurrencies',
            name='prefix',
            field=models.CharField(blank=True, help_text='This will be appended before the amount of this currency in the entire system', max_length=10, null=True, verbose_name='Prefix'),
        ),
        migrations.AlterField(
            model_name='historicalcurrencies',
            name='sufix',
            field=models.CharField(blank=True, help_text='This will be appended after the amount of this currency in the entire system', max_length=10, null=True, verbose_name='Sufix'),
        ),
    ]
