# Generated by Django 2.1.1 on 2018-09-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0002_auto_20180921_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencies',
            name='withdraw_auto_approve',
            field=models.BooleanField(default=False, help_text='Mark this if the withdraw must be automatically approved by the system', verbose_name='Auto approve withdraw'),
        ),
        migrations.AddField(
            model_name='historicalcurrencies',
            name='withdraw_auto_approve',
            field=models.BooleanField(default=False, help_text='Mark this if the withdraw must be automatically approved by the system', verbose_name='Auto approve withdraw'),
        ),
    ]
