# Generated by Django 2.1 on 2018-08-10 19:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0002_historicalaccounts_historicalbankaccounts_historicalbankwithdraw_historicalcryptowithdraw_historical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='Profile data'),
        ),
    ]
