# Generated by Django 2.1 on 2018-10-15 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0003_auto_20180927_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankwithdraw',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('reversed', 'Reversed'), ('paid', 'Paid')], default='requested', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='cryptowithdraw',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('reversed', 'Reversed'), ('paid', 'Paid')], default='requested', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('disapproved', 'Disapproved'), ('approved', 'Approved')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='type',
            field=models.CharField(choices=[('id_front', 'ID front'), ('id_back', 'ID back'), ('selfie', 'Selfie with ID'), ('social_contract', 'Social contract'), ('residence', 'Proof of address')], max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='historicalbankwithdraw',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('reversed', 'Reversed'), ('paid', 'Paid')], default='requested', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalcryptowithdraw',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('reversed', 'Reversed'), ('paid', 'Paid')], default='requested', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('reversed', 'Reversed'), ('withdraw', 'Withdraw'), ('income', 'Income'), ('investment', 'Investment'), ('tbsa', 'TBSA')], max_length=30, verbose_name='Type'),
        ),
    ]
