# Generated by Django 2.0.1 on 2018-01-16 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0003_auto_20180106_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to='')),
                ('type', models.CharField(choices=[('driver', 'driver'), ('id', 'id'), (
                    'selfie', 'selfie'), ('contract', 'contract')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'pending'), (
                    'disapproved', 'disapproved'), ('approved', 'approved')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                           related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
