# Generated by Django 2.1.1 on 2018-09-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0003_auto_20180810_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencies',
            old_name='symbol',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='historicalcurrencies',
            old_name='symbol',
            new_name='code',
        ),
        migrations.AlterUniqueTogether(
            name='currencies',
            unique_together={('code', 'type')},
        ),
    ]
