# Generated by Django 2.0.1 on 2018-01-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0004_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('disapproved', 'disapproved'), (
                'approved', 'approved')], default='pending', max_length=20),
        ),
    ]
