# Generated by Django 2.1.1 on 2018-09-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0004_auto_20180912_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='historicalcurrencies',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Code'),
        ),
    ]
