# Generated by Django 2.1.1 on 2018-09-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0005_auto_20180912_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencies',
            name='is_fiat',
            field=models.BooleanField(default=False, help_text='Mark this field if the currency is a fiduciary one', verbose_name='Is FIAT'),
        ),
        migrations.AddField(
            model_name='currencies',
            name='prefix',
            field=models.CharField(help_text='This will be appended before the amount of this currency in the entire system', max_length=10, null=True, verbose_name='Prefix'),
        ),
        migrations.AddField(
            model_name='currencies',
            name='sufix',
            field=models.CharField(help_text='This will be appended after the amount of this currency in the entire system', max_length=10, null=True, verbose_name='Sufix'),
        ),
        migrations.AddField(
            model_name='historicalcurrencies',
            name='is_fiat',
            field=models.BooleanField(default=False, help_text='Mark this field if the currency is a fiduciary one', verbose_name='Is FIAT'),
        ),
        migrations.AddField(
            model_name='historicalcurrencies',
            name='prefix',
            field=models.CharField(help_text='This will be appended before the amount of this currency in the entire system', max_length=10, null=True, verbose_name='Prefix'),
        ),
        migrations.AddField(
            model_name='historicalcurrencies',
            name='sufix',
            field=models.CharField(help_text='This will be appended after the amount of this currency in the entire system', max_length=10, null=True, verbose_name='Sufix'),
        ),
    ]
