# Generated by Django 2.0.1 on 2018-01-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0005_auto_20180116_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='type',
            field=models.CharField(choices=[('id_front', 'id_front'), ('id_back', 'id_back'), ('selfie', 'selfie'), ('contract', 'contract')], max_length=20),
        ),
    ]
