# Generated by Django 2.0.1 on 2018-01-18 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0006_auto_20180116_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'ordering': [
                'status'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterField(
            model_name='currencies',
            name='symbol',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
