# Generated by Django 2.1.1 on 2018-09-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0006_auto_20180917_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencies',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='historicalcurrencies',
            old_name='status',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='currencies',
            name='type',
            field=models.CharField(choices=[('checking', 'Checking'), ('investment', 'Investment')], default='checking', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='historicalcurrencies',
            name='type',
            field=models.CharField(choices=[('checking', 'Checking'), ('investment', 'Investment')], default='checking', max_length=20, verbose_name='Type'),
        ),
    ]
