# Generated by Django 2.0.1 on 2018-01-27 13:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0007_auto_20180118_0243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(
                    default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4,
                                        editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(
                    max_length=100, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=8,
                                               default=Decimal('0.00'), max_digits=20)),
                ('type', models.CharField(choices=[
                 ('deposit', 'deposit'), ('withdrawal', 'withdrawal')], max_length=30, verbose_name='Type')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='statement', to='exchange_core.Accounts', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Statement',
                'verbose_name_plural': 'Statement',
            },
        ),
    ]
