# Generated by Django 2.0.2 on 2018-02-12 01:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0013_auto_20180209_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencies',
            name='withdraw_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Max Withdraw'),
        ),
        migrations.AddField(
            model_name='currencies',
            name='withdraw_max',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Max Withdraw'),
        ),
        migrations.AddField(
            model_name='currencies',
            name='withdraw_min',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=20, verbose_name='Min Withdraw'),
        ),
        migrations.AddField(
            model_name='currencies',
            name='withdraw_receive_hours',
            field=models.IntegerField(default=48),
        ),
    ]
