# Generated by Django 2.0.2 on 2018-02-18 22:04

from django.db import migrations
import exchange_core.managers


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0015_auto_20180212_0150'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', exchange_core.managers.CustomUserManager()),
            ],
        ),
    ]
