# Generated by Django 2.0.2 on 2018-03-02 12:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0018_auto_20180301_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankwithdraw',
            name='profit',
            field=models.DecimalField(
                decimal_places=8, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AddField(
            model_name='cryptowithdraw',
            name='profit',
            field=models.DecimalField(
                decimal_places=8, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='statement',
            name='type',
            field=models.CharField(choices=[(
                'deposit', 'deposit'), ('withdraw', 'withdraw')], max_length=30, verbose_name='Type'),
        ),
    ]
