# Generated by Django 2.0.2 on 2018-03-02 16:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0020_auto_20180302_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencies',
            name='withdraw_fixed_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.005'), max_digits=20, verbose_name='Withdraw Fixed Fee'),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='withdraw_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.005'), max_digits=20, verbose_name='Withdraw Percent Fee'),
        ),
    ]
