# Generated by Django 2.0.2 on 2018-03-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0022_documents_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='reason',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='Disapproved reason'),
        ),
    ]
