# Generated by Django 2.0.2 on 2018-03-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0024_auto_20180306_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='status',
            field=models.CharField(choices=[('active', 'active'), (
                'inactive', 'inactive')], default='active', max_length=30, verbose_name='Status'),
        ),
    ]
