# Generated by Django 2.0.2 on 2018-03-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0024_auto_20180306_1427'),
        ('exchange_core', '0025_auto_20180306_1651'),
    ]

    operations = [
    ]
