# Generated by Django 2.0.2 on 2018-03-08 15:16

from django.db import migrations, models
import exchange_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0026_merge_20180306_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencies',
            name='icon',
            field=models.ImageField(
                blank=True, null=True, upload_to=exchange_core.models.get_file_path, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='file',
            field=models.ImageField(
                upload_to=exchange_core.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(
                blank=True, upload_to=exchange_core.models.get_file_path),
        ),
    ]
