# Generated by Django 2.0.1 on 2018-03-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0027_auto_20180308_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankwithdraw',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('reversed', 'reversed'), ('paid', 'paid')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='cryptowithdraw',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('reversed', 'reversed'), ('paid', 'paid')], default='requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='statement',
            name='type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('reverse', 'reverse'), ('withdraw', 'withdraw')], max_length=30, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='users',
            name='document_1',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='document_2',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
