# Generated by Django 2.0.1 on 2018-03-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0029_auto_20180319_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccounts',
            name='account_number_digit',
            field=models.CharField(
                max_length=5, null=True, verbose_name='Account number digit'),
        ),
        migrations.AddField(
            model_name='bankaccounts',
            name='agency_digit',
            field=models.CharField(
                max_length=5, null=True, verbose_name='Agency Digit'),
        ),
        migrations.AddField(
            model_name='statement',
            name='fk',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='statement',
            name='type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('reverse', 'reverse'), (
                'withdraw', 'withdraw'), ('income', 'income')], max_length=30, verbose_name='Type'),
        ),
    ]
