# Generated by Django 2.0.1 on 2018-03-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0033_auto_20180323_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencies',
            name='type',
            field=models.CharField(choices=[('checking', 'checking'), ('investment', 'investment')], default='checking', max_length=20),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='symbol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='currencies',
            unique_together={('symbol', 'type')},
        ),
    ]
