# Generated by Django 2.0.1 on 2018-05-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0035_auto_20180328_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='sponsor',
        ),
    ]
