# Generated by Django 2.0.1 on 2018-05-20 17:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0036_remove_users_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencies',
            name='tbsa_withdraw_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.005'), help_text='Transfer between system accounts', max_digits=20, verbose_name='TBSA Withdraw Percent Fee'),
        ),
        migrations.AddField(
            model_name='currencies',
            name='tbsa_withdraw_fixed_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.005'), help_text='Transfer between system accounts', max_digits=20, verbose_name='TBSA Withdraw Fixed Fee'),
        ),
    ]
