# Generated by Django 2.0.1 on 2018-05-20 17:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0037_auto_20180520_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencies',
            name='tbsa_withdraw_fee',
        ),
        migrations.RemoveField(
            model_name='currencies',
            name='tbsa_withdraw_fixed_fee',
        ),
        migrations.AddField(
            model_name='currencies',
            name='tbsa_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal(
                '0.0'), help_text='Transfer between system accounts', max_digits=20, verbose_name='TBSA Percent Fee'),
        ),
        migrations.AddField(
            model_name='currencies',
            name='tbsa_fixed_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal(
                '0.0'), help_text='Transfer between system accounts', max_digits=20, verbose_name='TBSA Fixed Fee'),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='withdraw_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal(
                '0.0'), max_digits=20, verbose_name='Withdraw Percent Fee'),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='withdraw_fixed_fee',
            field=models.DecimalField(decimal_places=8, default=Decimal(
                '0.0'), max_digits=20, verbose_name='Withdraw Fixed Fee'),
        ),
        migrations.AlterField(
            model_name='currencies',
            name='withdraw_min',
            field=models.DecimalField(decimal_places=8, default=Decimal(
                '0.0'), max_digits=20, verbose_name='Withdraw Min'),
        ),
    ]
