# Generated by Django 2.0.1 on 2018-05-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0038_auto_20180520_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('reverse', 'reverse'), ('withdraw', 'withdraw'), (
                'income', 'income'), ('investment', 'investment'), ('tbsa', 'tbsa')], max_length=30, verbose_name='Type'),
        ),
    ]
