# Generated by Django 2.0.1 on 2018-05-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0039_auto_20180525_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='complement',
            field=models.CharField(
                max_length=50, null=True, verbose_name='Complement'),
        ),
    ]
