# Generated by Django 2.0.1 on 2018-05-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0040_addresses_complement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='type',
            field=models.CharField(choices=[('deposit', 'deposit'), ('reverse', 'reverse'), ('withdraw', 'withdraw'), ('income', 'income'), ('investment', 'investment'), ('tbsa', 'tbsa'), ('course_subscription', 'course_subscription')], max_length=30, verbose_name='Type'),
        ),
    ]
