# Generated by Django 2.0.1 on 2018-05-28 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0041_auto_20180528_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='address_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address ID'),
        ),
    ]
