# Generated by Django 2.0.1 on 2018-06-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0042_accounts_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('inactive', 'Inactive'), ('approved_documentation', 'Approved documentation'), ('disapproved_documentation', 'Disapproved documentation')], default='created', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='users',
            name='type',
            field=models.CharField(choices=[('person', 'Person'), ('company', 'Company')], default='person', max_length=11, null=True, verbose_name='Type'),
        ),
    ]
