# Generated by Django 2.0.1 on 2018-06-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0043_auto_20180625_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
    ]
