# Generated by Django 2.0.1 on 2018-07-04 17:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0044_users_is_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankwithdraw',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='cryptowithdraw',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
