# Generated by Django 2.0.1 on 2018-07-04 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_core', '0045_auto_20180704_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankwithdraw',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cryptowithdraw',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
